### ISSUE TITLE
Upgrade from nwsapi 2.2.5 to 2.2.6 started issue with JEST + RTL test cases

### ISSUE THREAD

**Issue by sagar1111212121** [dperini/nwsapi#90]
Hello @dperini and team,

I found that upgrading nwsapi from 2.2.5 to 2.2.6 created an issue with the existing test cases written with JEST and RTL. it was all working fine in 2.2.5 just before sometime but as soon as, we did fresh npm install and almost 205 test cases stated failing which just worked fine in last couple of pipelines.

I dont know the exact reason for failures other than test log (Mostly around UserEvent.click and screen.getByTestId started failing)

We faced similar kind of issue when it was upgraded from 2.2.2 to 2.2.3 (Later 2.2.4 was released with quick fix which worked). 

Is there anyone facing similar issue?

**Comment by dperini** [comment]
@sagar1111212121 
thank you for reporting the issue.
I did run all my tests and jsdom/wpt test suite with no errors. So I don't know where to start looking for problems.
Could you kindly provide a test failing or send a log of the errors from your environment for me to check ?

**Comment by sagar1111212121** [comment]
Hi @dperini 

Thanks for the quick response. lease find below screenshots for your reference

![image](https://github.com/dperini/nwsapi/assets/6546417/a55f3489-ac81-4aa1-9ff2-33c4ee699c0c)

![image](https://github.com/dperini/nwsapi/assets/6546417/e8dde23a-2fe5-4b0e-befc-09304a6af62d)

![image](https://github.com/dperini/nwsapi/assets/6546417/72c11ff1-ec44-4008-861c-9a5da67d57ae)

There are almost 100 tests started failing because of above error.

**Comment by nhardy** [comment]
@dperini: I've traced the issue back to this line here: https://github.com/dperini/nwsapi/blob/32da18d5ca9c39057ff8083c87ae0ebf58dbe977/src/nwsapi.js#L1087

It looks like `if(n===e)break;` appears outside the `while` loop which causes this syntax error.

**Comment by sagar1111212121** [comment]
For a quick workaround to unblock the pipeline, I have added below code in my 'setupTests.ts' and it is working fine for time being. 

`global.getComputedStyle = function getComputedStyleMock(): any {
  return {
    getPropertyValue: () => undefined,
  };
};`

**Comment by mamang126** [comment]
Also another fix is override the version of the peer dependency:

```
"devDependencies": {
  "nwsapi": "2.2.5"
},
"overrides": {
  "nwsapi": "$nwsapi"
}
```

**Comment by dperini** [comment]
@sagar1111212121 
I believe I did find out the reason of the regression. Your suggested point of failure seems to be correct.
This is what happened ... The line that you pointed out existed before as part of the ":focus-within" resolution.
In the last 2.2.6 release I fixed the checking order of ":focus-within" to happen before the ":focus" pseudo-class.
However since the ":focus-within" pseudo-class was never tested thoroughly, now it is part of the accepted selectors.
Unfortunately the resolver for that was never tried nor executed. That's the reason of the current bug.
I am already working on the patch, I hope to be able to fix this today.

Thank you for raising the alert on this and for giving me a starting point about where to look for the fix.

**Comment by doberkofler** [comment]
@sagar1111212121 I'm also having this problem and explicitly adding a dependency can be used as a workaround

**Comment by nandeshwarshubh** [comment]
We are also facing the same issue, downgrading to 2.2.5 worked.

**Comment by dperini** [comment]
@sagar1111212121
please check the fixes I did commit today in this repository.
I will wait for a few confirmations and do minor release 2.2.7 tomorrow.

**Comment by alvarogfn** [comment]
For anyone using yarn, this workaround worked for me:

```json
"resolutions": {
  "**/nwsapi": "2.2.5"
}
```

**Comment by val1984** [comment]
For anyone using `pnpm`, put this in your `package.json` file until 2.2.7 is released:
```json
{
  "pnpm": {
    "overrides": {
      "nwsapi": "2.2.5"
    }
  }
}
```

**Comment by isc30** [comment]
hi, im also getting this issue

**Comment by dep** [comment]
@sagar1111212121 

> Thanks for the quick response. Please find below screenshots for your reference

Thanks for reporting this. Please consider pasting your error message as text instead of images so folks Googling the same error message can find pages like these.  🙏🏻

**Comment by aishwarya-tw** [comment]
@dperini We are also facing this issue and it is blocking one our release. Unfortunately we can't use the workaround in our case. Any idea when 2.2.7 will be released with the fix?

**Comment by dperini** [comment]
@aishwarya-tw and all affected users.
Sorry for the troiubles I just pushed the latest 2.2.7 release on NPM.
Please confirm that the ':focus-within' pseudo-class related regression is fixed.

**Comment by sagar1111212121** [comment]
@dperini I am checking it now and should be able to update in sometime.

**Comment by sagar1111212121** [comment]
> @sagar1111212121
> 
> > Thanks for the quick response. Please find below screenshots for your reference
> 
> Thanks for reporting this. Please consider pasting your error message as text instead of images so folks Googling the same error message can find pages like these. 🙏🏻

Yah, Didn't realize this. But will keep this in mind :)

**Comment by aishwarya-tw** [comment]
> @aishwarya-tw and all affected users. Sorry for the troiubles I just pushed the latest 2.2.7 release on NPM. Please confirm that the ':focus-within' pseudo-class related regression is fixed.

@dperini  Thank you so much for the quick action and timely release! 🙏🏼  I can confirm that the fix is working for us and our build pipeline is running all the way through!

**Comment by sagar1111212121** [comment]
@dperini 

> @aishwarya-tw and all affected users. Sorry for the troiubles I just pushed the latest 2.2.7 release on NPM. Please confirm that the ':focus-within' pseudo-class related regression is fixed.

@dperini - You rock.

All 1400 test cases passed without any issue now :) 

Thanks for the quick resolution.

**Comment by vonny29** [comment]
@dperini thank you so much for quick response, all my test cases are working again now. :)

**Comment by dperini** [comment]
@sagar1111212121 @val1984 @vonny29 and all users of "nwsapi" ...
Thank you for the collaboration, this allows for quick response time.
Just notifying me if it works or if it doesn't work, is an appreciated help.
Next step would be to provide a minimal test showing the error you get.

I am now tackling ':focus-visible' pseudo-class which in my tests is already working well (targeting release 2.2.8).
Then there is a WIP for including WPT as the base unit test for "nwsapi", this will grant less regression like this last one.
In the working queue I also have the resolver of the following pseudo-classes (if they make sense & there is demand for):

    rsrc_state: '(playing|paused|seeking|buffering|stalled|muted|volume-locked)' - (media resources state)
    disp_state: '(open|closed|modal|fullscreen|picture-in-picture)' - (element display state)
    time_state: '(current|past|future)' - (time dimensions)

and, on request, in the queue I also have an easy one like the :defined pseudo-class which have been requested by some.
Thank you all again.

**Comment by lakshman0369** [comment]
@dperini 
for us the below assertion is failing after upgrading the nwsapi from 2.2.5 to 2.2.7. When we fixed the version to 2.2.5 this assertion is working fine.
`expect(screen.getByRole('button')).toHaveStyle(
      'background-color: transparent'
    );`


![image](https://github.com/dperini/nwsapi/assets/54270674/db76e9d1-729f-40d5-80fd-590fd8a35302)


When ever the component is rendered, it is taking the active state background-color even though it isn't set to active. Please look into this issue.

**Comment by dperini** [comment]
@lakshman0369 
I will have a look in to this issue.
Thank you for reporting.

**Comment by Xe11o** [comment]
Reporting similar issue to the above

Assertion:
`
    expect(renderedTabs[0]).toHaveStyle(`
      color: rgb(0, 82, 204);
      background-color: white;
    `);
`

CSS:
![Screenshot 2023-07-14 at 19 55 39](https://github.com/dperini/nwsapi/assets/13576985/84340fb3-b0a9-42b1-a23a-9dced3a6c78d)


It fails because background-color has the hover value rather than the value it should have. Hover / active styles seem to be getting applied erroneously during the test.

**Comment by dperini** [comment]
@lakshman0369 @Xe11o
please see commit d8ac96549d5574f5a7f8eb479cd76be5a33b3925 it should be fixing the issue.
I saw it was related to :hover and :active pseudo-classes in your reports.

**Comment by bazanowsky** [comment]
Hi @dperini 
indeed this commit fixes the issue - I saw you already merged it to master - but the package is not updated on npm - using version 2.2.7 still have this bug. 

When you expect to publish this fix it to npm?

**Comment by dperini** [comment]
Closing as  completed.
Reopen if necessary.
